on:
  push:
    tags: ["v*"]
  pull_request:
    branches: ["*"]

name: Build and deploy
jobs:
  build:
    if: github.event_name == 'pull_request'
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install # will run `yarn install` command
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: format-check # will run `yarn build` command
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: build # will run `yarn build` command

  deploy:
    if: github.event_name != 'pull_request' && (startsWith(github.ref, 'refs/tags/v'))
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Install npm
        run: |
          npm i -g vsce
          npm install
      - name: Publish
        run: |
          echo $RELEASE_VERSION
          vsce publish -p $VSCODE_TOKEN --no-git-tag-version ${RELEASE_VERSION:1}
        env:
          VSCODE_TOKEN: ${{ secrets.VSCODE_TOKEN }}
